.\" $Id$
.Dd April 6, 2005
.Dt MOUNT_HFS 8
.Os
.Sh NAME
.Nm mount_hfs
.Nd mount an HFS file system
.Sh SYNOPSIS
.Nm mount_hfs
.Op Fl o Ar options
.Ar special node
.Sh DESCRIPTION
.Pp
The following options are supported:
.Bl -tag -width Ds
.It Fl o Ar options
.El
.Sh SEE ALSO
.Xr mount 8 ,
.Xr umount 8
